name: Deploy (io-web-profile-fn)

on:
  workflow_dispatch:

jobs:
  deploy_on_prod:
    uses: pagopa/dx/.github/workflows/legacy_deploy_pipelines.yaml@main
    name: Deploy on PROD
    secrets: inherit
    with:
      environment: 'prod'
      resource_group_name: 'io-p-itn-auth-webprof-rg-01'
      app_name: 'io-p-itn-auth-webprof-func-01'
      use_staging_slot: true
      use_private_agent: false
      health_check_path: '/api/v1/info'